<!--
Helper .qmd file that is called in index.qmd with a package name as input
and produces the same layout and output types for all tabs.
-->

```{r}
# The open issues and the open pull requests of a package are listed the same
# way: the title links to GitHub, the rest says who opened it and when.
issue_pr_table <- function(items) {
  items |>
    mutate(
      title = paste0(
        "<a href=\"",
        url,
        "\" target=\"_blank\">",
        htmltools::htmlEscape(title),
        "</a>"
      )
    ) |>
    select(number, title, author, opened) |>
    reactable(
      columns = list(
        number = colDef(name = "#", maxWidth = 70),
        title = colDef(name = "Title", html = TRUE),
        author = colDef(name = "Opened by", maxWidth = 140),
        opened = colDef(name = "Opened", maxWidth = 110)
      ),
      defaultSorted = list(opened = "desc"),
      searchable = TRUE,
      highlight = TRUE
    )
}

```

### Column {.tabset}

#### Activity

##### Column

###### Row

```{r}
#| output: asis
vbox("Number of contributors", "people", get_latest("contributors", pkg))
```

```{r}
#| output: asis
vbox("Number of forks", "diagram-2", get_latest("forks", pkg, default_return = 0))
```


```{r}
#| output: asis
vbox(
  "Number of open issues",
  "exclamation-circle",
  get_latest("open_issues", pkg, default_return = 0),
  href = paste0("https://github.com/palaeoverse/", pkg, "/issues")
)
```

```{r}
#| output: asis
vbox(
  "Number of open pull requests",
  "git",
  get_latest("open_pull_requests", pkg, default_return = 0),
  href = paste0("https://github.com/palaeoverse/", pkg, "/pulls")
)
```

```{r}
#| output: asis
vbox(
  "Average time to first response in issues (hours)",
  "stopwatch",
  round(latest_mean_response_time(pkg), 1)
)
```

```{r}
#| output: asis
vbox(
  "Weeks since last CRAN update",
  "arrow-counterclockwise",
  latest_release(pkg)[["n_weeks"]]
)
```

###### Row

```{r}
get_statistics("commits", pkg) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Cumulative number") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |> 
  e_toolbox(show = FALSE) |>
  e_title("Cumulative number of commits")
```


```{r}
get_statistics("lines_of_code", pkg) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Number of lines of code") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |> 
  e_toolbox(show = FALSE) |>
  e_title("Number of lines of code")
```

###### Row

```{r}
#| title: Open issues
issue_pr_table(open_issues(pkg))
```

```{r}
#| title: Open pull requests
issue_pr_table(open_prs(pkg))
```


#### Code quality

###### Row

```{r}
#| title: !expr 'title_tip("Code coverage (higher is better)", "Share of the lines of code of the package that are run when the test suite is executed.")'
get_statistics("code_coverage", pkg) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Code coverage") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |>
  e_toolbox(show = FALSE) |>
  e_title("Code coverage", subtext = "Higher is better")
```

```{r}
#| title: !expr 'title_tip("Average cyclomatic complexity (lower is better)", "Cyclomatic complexity counts the number of independent paths through a function (\"if\" conditions, \"for\" and \"while\" loops, etc.). The function complexity increases with the number of paths.")'
get_statistics("mean_cyclomatic_complexity", pkg) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Average cyclomatic complexity") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |>
  e_toolbox(show = FALSE) |>
  e_title("Average cyclomatic complexity", subtext = "Lower is better")
```


###### Row

```{r}
#| title: !expr 'title_tip("Code coverage (higher is better)", "Share of the lines of code of the package that are run when the test suite is executed.")'
coverage_by_function(pkg) |>
  reactable(
    columns = list(
      function_name = colDef(name = "Function"),
      coverage = colDef(
        name = "Coverage (%)",
        format = colFormat(digits = 1)
      ),
      lines = colDef(name = "Lines"),
      hits = colDef(name = "Hits"),
      misses = colDef(name = "Misses")
    ),
    defaultSorted = list(coverage = "asc"),
    searchable = TRUE,
    highlight = TRUE
  )
```

```{r}
#| title: !expr 'title_tip("Average cyclomatic complexity (lower is better)", "Cyclomatic complexity counts the number of independent paths through a function (\"if\" conditions, \"for\" and \"while\" loops, etc.). The function complexity increases with the number of paths.")'
cyclocomp_by_function(pkg) |>
  reactable(
    columns = list(
      function_name = colDef(name = "Function"),
      complexity = colDef(name = "Cyclomatic complexity")
    ),
    defaultSorted = list(complexity = "desc"),
    searchable = TRUE,
    highlight = TRUE
  )
```

#### Impact

###### Row

```{r}
#| output: asis
vbox("CRAN downloads", "cloud-download", get_latest("cran_downloads", pkg))
```

```{r}
#| output: asis
vbox("GitHub stars", "star", get_latest("github_stars", pkg, default_return = 0))
```

```{r}
#| output: asis
vbox("Citations", "book", get_latest("citations", pkg, default_return = 0))
```

```{r}
#| output: asis
vbox(
  "Reverse dependencies",
  "boxes",
  get_latest("reverse_dependencies", pkg, default_return = 0)
)
```

###### Row

```{r}
# One point a week is plenty for a series this long, and much lighter to draw
get_statistics("cran_downloads", pkg) |>
  slice(seq(1, n(), by = 7)) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Cumulative number") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |> 
  e_toolbox(show = FALSE) |>
  e_title("Cumulative number of CRAN downloads")
```


```{r}
get_statistics("github_stars", pkg) |>
  e_charts(x = date) |>
  e_line(serie = value, name = "Cumulative number") |>
  e_legend(show = FALSE) |>
  e_tooltip(trigger = "axis") |>
  e_datazoom(type = "slider") |> 
  e_toolbox(show = FALSE) |>
  e_title("Cumulative number of Github stars")
```
